version: '3.8'

services:
  vietnam-api-staging:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vietnam-admin-api-staging
    ports:
      - "8101:8100"  # Different port for staging
    environment:
      - PORT=8100
      - GIN_MODE=release
      - DATA_PATH=/root/data
      - ENVIRONMENT=staging
    volumes:
      # Mount JSON data files (if you want to update them without rebuilding)
      - ./data/province.json:/root/data/province.json:ro
      - ./data/ward.json:/root/data/ward.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vietnam-api-staging.rule=Host(`staging-api.vietnam-admin.local`)"
      - "traefik.http.services.vietnam-api-staging.loadbalancer.server.port=8100"
    networks:
      - vietnam-staging-network

  # Optional: Redis for caching (staging)
  redis-staging:
    image: redis:7-alpine
    container_name: vietnam-redis-staging
    ports:
      - "6380:6379"  # Different port for staging
    command: redis-server --appendonly yes
    volumes:
      - redis-staging-data:/data
    restart: unless-stopped
    networks:
      - vietnam-staging-network

  # Optional: Nginx reverse proxy (staging)
  nginx-staging:
    image: nginx:alpine
    container_name: vietnam-nginx-staging
    ports:
      - "8080:80"  # Different port for staging
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vietnam-api-staging
    restart: unless-stopped
    networks:
      - vietnam-staging-network

volumes:
  redis-staging-data:
    driver: local

networks:
  vietnam-staging-network:
    driver: bridge 